---

plugins:
  - /usr/lib/ladspa/amp_1181.so
  - /usr/lib/ladspa/delay_1898.so
  - /usr/lib/ladspa/ZamGEQ31-ladspa.so
  - /usr/lib/ladspa/ZamGate-ladspa.so
  - /usr/lib/ladspa/ZamTube-ladspa.so

routes:
  - [ ModPro:receive_out_1, "system:playback_1" ]
  - [ ModPro:receive_out_1, "system:playback_2" ]
  - [ "Network In:out_1", ModPro:receive_in_1 ]

chains:
  receive:
    inputs:
      - input_gain.Input
    outputs:
      - output_gain.Output
    effects:
      - name: input_gain
        type: Simple amplifier
        controls:
          Amps gain (dB): 0
        wires:
          Output:
            - delay.Input
            - gate.Sidechain Input
      - name: delay
        type: Simple delay line, linear interpolation
        controls:
          Delay Time (s): .150
          Max Delay (s): .2
        wires:
          Output:
            - gate.Audio Input 1
      - name: gate
        type: ZamGate
        controls:
          Sidechain: 1
          Threshold: -65
          Attack: 25
          Release: 25
          Max gate close: -.inf
        wires:
          Audio Output 1:
            - tube.Audio Input 1
      - name: tube
        type: ZamTube
        controls:
          Tone Stack Model: 0 # 0 - 24
          Tube Drive: 0
          Bass: -2
          Mids: 0
          Treble: 0
        wires:
          Audio Output 1:
            - output_gain.Input
      - name: output_gain
        type: Simple amplifier
        controls:
          Amps gain (dB): 6
  transmit:
    inputs:
      - eq.Audio Input 1
    outputs:
      - eq.Audio Output 1
    effects:
      - name: eq
        type: ZamGEQ31
        controls:
          Master Gain: 0
          32Hz: -12
          40Hz: -12
          50Hz: -12
          63Hz: -12
          79Hz: -12
          100Hz: 12
          126Hz: 12
          158Hz: 8
          200Hz: 2
          1584Hz: 1
          1997Hz: 2
          2514Hz: 4
          3165Hz: 7
          3986Hz: 12
          5017Hz: -12
          6318Hz: -12
          7963Hz: -12
          10032Hz: -12
          12662Hz: -12
          16081Hz: -12
          20801Hz: -12
